timeout: 20

expectedTitle: Max_Iterational Product

elements:
      
      productButton: 
            findBy: xpath
            locator: //*[@class="nav-link dropdown-toggle"][@href="/products/"]
      prdouctListContainer:
            findBy: xpath
            locator: //*[@class="product-cards--list"]
      nutritionalHeadingForLearnMore:
            findBy: xpath
            locator: //*[@src="../images/product1.png"]
      nutritionalsScrollLearnMore:
            findBy: xpath
            locator: //a[@href='/products/nutritionals' and text()='Learn More']
      imageBesideSwitchHeadingLearnMore:
            findBy: xpath
            locator: //*[@src="../images/img-weight-management.jpg"]
      switchWeightHeadingLearnMore:
            findBy: xpath
            locator: //*[@class="text-uppercase" and text() = "The Meta-Switch Weight Management System" ]
      switchWeightManagementLearnMore:
            findBy: xpath
            locator: //*[@href="/products/switch"][text()="Learn More"]
      oppurtunityHoover:
            findBy: xpath
            locator: //*[@href="/join/"]//span[text()="Opportunity"]
      hooverImageList:
            findBy: xpath
            locator: //*[@class='overlay-img bg-blue']
      
      productsWithPurposeHoover:
            findBy: xpath
            locator: //a[@href="/products/"]//span[text()="PRODUCTS WITH PURPOSE"]
      maxGivesBackHoover:
            findBy: xpath
            locator: //a[@href="/company/why-max/max-difference/#max_gives_back"]//span[text()="MAX GIVES BACK"]
      
      weightManagementSwitchOption:
            findBy: xpath
            locator: //*[@class="col-sm-6"]//div[@class="inner-drop"]//ul//li//a[text()="Switch"]
      beautyFoundationOption:
            findBy: xpath
            locator: //a[@href="/products/beauty/foundation/"][text()="Foundation"]
      buyNowButton:
            findBy: xpath
            locator: //*[@id="for_sponsor_button"]
      buyNowOpenWindow:
            findBy: xpath
            locator: //*[@id="joinChooseModalLongTitle"]
      helpCenterOption:
            findBy: xpath
            locator: //*[@href="/my-max/faqs/"]
     
    